const constants = {
  CREATE_HISTORY_ITEM: 'ADD_HISTORY_ITEM',
  DELETE_HISTORY: 'DELETE_HISTORY',
  ADD_ACTIVE_POINTS: 'ADD_ACTIVE_POINTS',
  CLEAR_ACTIVE_POINTS: 'CLEAR_ACTIVE_POINTS'
};

export default constants;
